version: "3"

services:
#  mysql:
#    image: mysql:5.7.21
#    ports:
#      - "${LOCAL_DB_PORT}:3306"
#    volumes:
#      - "${LOCAL_PATH_TO_DB}:/var/lib/mysql"
#      - "./tests/Data:/var/lib/mysql-files:rw"
#    environment:
#      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
#      MYSQL_DATABASE: "${DB_DATABASE}"
#      MYSQL_USER: "${DB_USERNAME}"
#      MYSQL_PASSWORD: "${DB_PASSWORD}"
#
#  php:
#    build:
#      context: ./docker/php
  app:
    build: 
      context: ./docker/app
      args:
        XDEBUG_REMOTE_ENABLE: ${XDEBUG_REMOTE_ENABLE}
        XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
        XDEBUG_REMOTE_AUTO_START: ${XDEBUG_REMOTE_AUTO_START}
        XDEBUG_REMOTE_CONNECT_BACK: ${XDEBUG_REMOTE_CONNECT_BACK}
        XDEBUG_IDEKEY: ${XDEBUG_IDEKEY}
    ports:
      - "${LOCAL_HTTP_PORT}:80"
    volumes:
      - ${HOST_VOLUME}:${VOLUME}
      - ${HOST_VOLUME}/${APACHE_LOG}:/var/log/apache2:rw
    depends_on:
      - mysql
      - redis

  mysql:
    build: ./docker/mysql
    ports:
      - "${LOCAL_DB_PORT}:3306"
    volumes:
      - ${HOST_VOLUME}/${LOCAL_PATH_TO_DB}:/var/lib/mysql
      - ${HOST_VOLUME}/storage/tmp:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  redis:
    image: redis:latest

