version: "3"

services:
#  mysql:
#    image: mysql:5.7.21
#    ports:
#      - "${LOCAL_DB_PORT}:3306"
#    volumes:
#      - "${LOCAL_PATH_TO_DB}:/var/lib/mysql"
#      - "./tests/Data:/var/lib/mysql-files:rw"
#    environment:
#      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
#      MYSQL_DATABASE: "${DB_DATABASE}"
#      MYSQL_USER: "${DB_USERNAME}"
#      MYSQL_PASSWORD: "${DB_PASSWORD}"
#
#  php:
#    build:
#      context: ./docker/php
  app:
    build: 
      context: ./docker/app
      args:
        XDEBUG_REMOTE_ENABLE: ${XDEBUG_REMOTE_ENABLE}
        XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
        XDEBUG_REMOTE_AUTO_START: ${XDEBUG_REMOTE_AUTO_START}
        XDEBUG_REMOTE_CONNECT_BACK: ${XDEBUG_REMOTE_CONNECT_BACK}
        XDEBUG_IDEKEY: ${XDEBUG_IDEKEY}
    ports:
      - "${LOCAL_HTTP_PORT}:80"
    volumes:
      - ${HOST_VOLUME}:${VOLUME}
      - ${HOST_VOLUME}/${APACHE_LOG}:/var/log/apache2:rw
      - ${HOST_VOLUME}/docker/app/resolv.conf:/etc/resolv.conf
      - ${HOST_VOLUME}/docker/app/ldap/ca.pem:/etc/ldap/ca.pem
      - ${HOST_VOLUME}/docker/app/ldap/ldap.conf:/etc/ldap/ldap.conf
      - ${HOST_VOLUME}/docker/app/dhcp/dbclient.conf:/etc/dhcp/dbclient.conf
      - ${HOST_VOLUME}/docker/app/hostname:/etc/hostname
      - ${HOST_VOLUME}/docker/app/sssd/sssd.conf:/etc/sssd/sssd.conf
      - ${HOST_VOLUME}/docker/app/sudoers:/etc/sudoers
    depends_on:
      - mysql
      - redis
    extra_hosts:
      - "PNG-DC1.PANDGASSOCIATES.COM PNG-DC1:192.168.25.162"
      - "PNG-DC2.PANDGASSOCIATES.COM PNG-DC2:192.168.25.163"

    hostname: "DRICHTER_DOCK1"
    domainname: "PANDGASSOCIATES.COM"

  mysql:
    build: ./docker/mysql
    ports:
      - "${LOCAL_DB_PORT}:3306"
    volumes:
      - ${HOST_VOLUME}/${LOCAL_PATH_TO_DB}:/var/lib/mysql
      - ${HOST_VOLUME}/storage/tmp:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  redis:
    image: redis:latest




